export const BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzAwNzQzLCJpYXQiOjE3NDQyMTQzNDMsImp0aSI6IjY5NDk3MWY5NWNmNjQxZjk4NzI3MmVlODA5ZjEwNGZmIiwidXNlcl9pZCI6M30.eIXSbprFW4_vG9NCqvNBoH5bggSIYWSQL8tDE6of6ow"
// Error messages

export const REQUIRED_FIELD = "*This field is required"
