export const BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTEyOTE5LCJpYXQiOjE3NDI4MjY1MTksImp0aSI6IjAzY2RmNDUyOTUwZjQ5Y2M4NDAxN2Y3ZmRiNzJmMWRlIiwidXNlcl9pZCI6M30.5P0sI9_5ZuJvAhbrbKNW3HvE_fSXQzAyYaabvKVY4_E"
// Error messages

export const REQUIRED_FIELD = "*This field is required"